export const dressData = {
    outfits: [
      {
        _user: null,
        approval_user: {
          _id: "60b102f8be9fc41581d2fd31",
          username: "anastasia@intelistyle.co.uk",
        },
        approved: 2,
        bodytype: [],
        brand_group: null,
        garments: [
          {
            _id: "62c699db39c7fe91d77f2e3b",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [0, 4],
            chatbot_id: null,
            colour: {
              h: 0.5,
              name: "silver",
              s: 0.03030303030303034,
              v: 0.7764705882352941,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/626789b81e7bdd00301bfa6a/02ade394-9e98-4e85-9965-c78ebbe3b987.jpg",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/08714f50aed88261382f4155c3e16b91bbba76f7.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/08714f50aed88261382f4155c3e16b91bbba76f7_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/08714f50aed88261382f4155c3e16b91bbba76f7.jpg",
                segmentation_data: null,
                server_image_filename:
                  "08714f50aed88261382f4155c3e16b91bbba76f7.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "women",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [0, 1, 2, 5, 7, 8, 9, 10, 11],
            persona: [1, 3, 4],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/626789b81e7bdd00301bfa6a",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Trousers"],
            remote_product_description: null,
            remote_product_id: "626789b81e7bdd00301bfa6a",
            remote_product_size: null,
            remote_product_title: "Straight shortened trousers",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [1, 2, 3],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [],
            translations: null,
            updatedAt: "Tue, 12 Jul 2022 12:28:27 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/626789b81e7bdd00301bfa6a",
                variant_id: "default",
              },
            ],
            weather: [0, 1, 4, 5, 6, 7],
          },
          {
            _id: "62c699db39c7fe91d77f2ecd",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [0, 1, 2, 3, 4],
            chatbot_id: null,
            colour: {
              h: 0.14102564102564094,
              name: "dimgray",
              s: 0.11304347826086954,
              v: 0.45098039215686275,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/626789dc1e7bdd00301bfbad/55625b37-97c9-4de5-b707-ff8a15b3236d.jpg",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/e54bee4945c9e3caffb304fc5e16d1b77af4b279.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/e54bee4945c9e3caffb304fc5e16d1b77af4b279_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/e54bee4945c9e3caffb304fc5e16d1b77af4b279.jpg",
                segmentation_data: null,
                server_image_filename:
                  "e54bee4945c9e3caffb304fc5e16d1b77af4b279.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "women",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [0, 1, 5, 6, 7, 8, 10, 11, 15],
            persona: [0, 4],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/626789dc1e7bdd00301bfbad",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Tops"],
            remote_product_description: null,
            remote_product_id: "626789dc1e7bdd00301bfbad",
            remote_product_size: null,
            remote_product_title: "Flower Print Shirt",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [7, 8, 9],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [0],
            translations: null,
            updatedAt: "Thu, 07 Jul 2022 12:43:38 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/626789dc1e7bdd00301bfbad",
                variant_id: "default",
              },
            ],
            weather: [0, 1, 2, 4, 5, 6, 7, 9],
          },
          {
            _id: "62c699db39c7fe91d77f2e71",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [0, 1, 2, 3, 4],
            chatbot_id: null,
            colour: {
              h: 0.12500000000000014,
              name: "dimgray",
              s: 0.039603960396039604,
              v: 0.396078431372549,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/626789c01e7bdd00301bfae4/d39d3e7b-6f1f-4676-99e9-a8ab3e8a6b90.jpg",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/91499d41174eeee050cb1f66ac7bb69c12cd01ed.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/91499d41174eeee050cb1f66ac7bb69c12cd01ed_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/91499d41174eeee050cb1f66ac7bb69c12cd01ed.jpg",
                segmentation_data: null,
                server_image_filename:
                  "91499d41174eeee050cb1f66ac7bb69c12cd01ed.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "women",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [11, 15],
            persona: [0, 1, 3, 4],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/626789c01e7bdd00301bfae4",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Footwear"],
            remote_product_description: null,
            remote_product_id: "626789c01e7bdd00301bfae4",
            remote_product_size: null,
            remote_product_title: "Mary Jane Leather Muli",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [7, 8, 9],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [],
            translations: null,
            updatedAt: "Tue, 12 Jul 2022 11:09:51 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/626789c01e7bdd00301bfae4",
                variant_id: "default",
              },
            ],
            weather: [0, 1, 3, 5, 7],
          },
          {
            _id: "62c699db39c7fe91d77f2e66",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [0, 1, 2, 3, 4],
            chatbot_id: null,
            colour: {
              h: 0.125,
              name: "silver",
              s: 0.021505376344085947,
              v: 0.7294117647058823,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/626789bf1e7bdd00301bfaca/989d668a-010f-4f31-9daa-5aa0a9eba247.jpg",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/bd823798d7f704ade9acf128bbc25bb64bc9af8a.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/bd823798d7f704ade9acf128bbc25bb64bc9af8a_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/bd823798d7f704ade9acf128bbc25bb64bc9af8a.jpg",
                segmentation_data: null,
                server_image_filename:
                  "bd823798d7f704ade9acf128bbc25bb64bc9af8a.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "women",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [],
            persona: [0, 1, 3],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/626789bf1e7bdd00301bfaca",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Bags"],
            remote_product_description: null,
            remote_product_id: "626789bf1e7bdd00301bfaca",
            remote_product_size: null,
            remote_product_title: "Logo Print Clutch",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [1, 2, 3],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [],
            translations: null,
            updatedAt: "Tue, 12 Jul 2022 11:09:36 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/626789bf1e7bdd00301bfaca",
                variant_id: "default",
              },
            ],
            weather: [0, 1, 2, 3, 4, 5, 6, 7],
          },
          {
            _id: "62c699db39c7fe91d77f2e4e",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [0, 1, 2, 3, 4],
            chatbot_id: null,
            colour: {
              h: 0.05172413793103444,
              name: "gray",
              s: 0.21804511278195496,
              v: 0.5215686274509804,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/626789bb1e7bdd00301bfa93/903eb9fe-7a77-4bf4-aeac-f18740a757ef.jpg",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/70bd2308dfafe9de69ac049b646b1568b3a435fe.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/70bd2308dfafe9de69ac049b646b1568b3a435fe_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/70bd2308dfafe9de69ac049b646b1568b3a435fe.jpg",
                segmentation_data: null,
                server_image_filename:
                  "70bd2308dfafe9de69ac049b646b1568b3a435fe.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "women",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [],
            persona: [0, 3, 4],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/626789bb1e7bdd00301bfa93",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Accessories"],
            remote_product_description: null,
            remote_product_id: "626789bb1e7bdd00301bfa93",
            remote_product_size: null,
            remote_product_title: "Bilateral belt with a monogram",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [4, 5, 6],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [],
            translations: null,
            updatedAt: "Tue, 12 Jul 2022 11:09:10 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/626789bb1e7bdd00301bfa93",
                variant_id: "default",
              },
            ],
            weather: [0, 1, 2, 3, 4, 5, 6, 7],
          },
        ],
        market_id: [],
        occasion: [],
        outfit_id: "62c6d53e2a6b3e031c3c4a9f",
        outfit_image_url:
          "https://intelistyle-texel.s3.eu-west-1.amazonaws.com/looks/female/626789b81e7bdd00301bfa6a.png",
        persona: [],
        ranking: {
          "626789b81e7bdd00301bfa6a": 1,
          "626789bb1e7bdd00301bfa93": 4,
          "626789bf1e7bdd00301bfaca": 3,
          "626789c01e7bdd00301bfae4": 2,
          "626789dc1e7bdd00301bfbad": 0,
        },
        season: null,
        skintone: [],
        source: null,
        styling_filters: [],
        type: "complete_the_look",
        weather: [],
      },
      {
        _user: null,
        approval_user: null,
        approved: 2,
        bodytype: [],
        brand_group: null,
        garments: [
          {
            _id: "62c699db39c7fe91d77f2e91",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [],
            chatbot_id: null,
            colour: {
              h: 0.0666666666666667,
              name: "dimgray",
              s: 0.219298245614035,
              v: 0.447058823529412,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/626789ca1e7bdd00301bfb29/e1fbd46d-3cc3-40c6-a2fb-3a363cf8c1b6.png",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/f1a5556c44db29bca91f7dfaf3c1da9c40abbe4b.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/f1a5556c44db29bca91f7dfaf3c1da9c40abbe4b_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/f1a5556c44db29bca91f7dfaf3c1da9c40abbe4b.jpg",
                segmentation_data: null,
                server_image_filename:
                  "f1a5556c44db29bca91f7dfaf3c1da9c40abbe4b.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "women",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [0, 11],
            persona: [0],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/626789ca1e7bdd00301bfb29",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Dresses"],
            remote_product_description: null,
            remote_product_id: "626789ca1e7bdd00301bfb29",
            remote_product_size: null,
            remote_product_title: "D&G dress",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [7, 8, 9],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [0],
            translations: null,
            updatedAt: "Thu, 07 Jul 2022 12:43:53 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/626789ca1e7bdd00301bfb29",
                variant_id: "default",
              },
            ],
            weather: [1, 2, 3, 8],
          },
          {
            _id: "62c699db39c7fe91d77f2e7a",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [0, 1, 2, 3, 4],
            chatbot_id: null,
            colour: {
              h: 0.06666666666666682,
              name: "gainsboro",
              s: 0.10638297872340424,
              v: 0.9215686274509803,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/626789c21e7bdd00301bfaf6/6a74d173-dfed-4204-b605-e9abfab06c7a.jpg",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/a96a3ec7e9272397845a1fc28a303159fce842e2.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/a96a3ec7e9272397845a1fc28a303159fce842e2_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/a96a3ec7e9272397845a1fc28a303159fce842e2.jpg",
                segmentation_data: null,
                server_image_filename:
                  "a96a3ec7e9272397845a1fc28a303159fce842e2.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "women",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [],
            persona: [0, 1],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/626789c21e7bdd00301bfaf6",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Footwear"],
            remote_product_description: null,
            remote_product_id: "626789c21e7bdd00301bfaf6",
            remote_product_size: null,
            remote_product_title: "Sandals",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [1, 2, 3],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [],
            translations: null,
            updatedAt: "Tue, 12 Jul 2022 12:03:12 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/626789c21e7bdd00301bfaf6",
                variant_id: "default",
              },
            ],
            weather: [1, 3, 5],
          },
          {
            _id: "62c699db39c7fe91d77f2e66",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [0, 1, 2, 3, 4],
            chatbot_id: null,
            colour: {
              h: 0.125,
              name: "silver",
              s: 0.021505376344085947,
              v: 0.7294117647058823,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/626789bf1e7bdd00301bfaca/989d668a-010f-4f31-9daa-5aa0a9eba247.jpg",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/bd823798d7f704ade9acf128bbc25bb64bc9af8a.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/bd823798d7f704ade9acf128bbc25bb64bc9af8a_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/bd823798d7f704ade9acf128bbc25bb64bc9af8a.jpg",
                segmentation_data: null,
                server_image_filename:
                  "bd823798d7f704ade9acf128bbc25bb64bc9af8a.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "women",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [],
            persona: [0, 1, 3],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/626789bf1e7bdd00301bfaca",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Bags"],
            remote_product_description: null,
            remote_product_id: "626789bf1e7bdd00301bfaca",
            remote_product_size: null,
            remote_product_title: "Logo Print Clutch",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [1, 2, 3],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [],
            translations: null,
            updatedAt: "Tue, 12 Jul 2022 11:09:36 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/626789bf1e7bdd00301bfaca",
                variant_id: "default",
              },
            ],
            weather: [0, 1, 2, 3, 4, 5, 6, 7],
          },
          {
            _id: "62c699db39c7fe91d77f2e4b",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [0, 1, 2, 3, 4],
            chatbot_id: null,
            colour: {
              h: 0.14529914529914525,
              name: "gray",
              s: 0.2746478873239437,
              v: 0.5568627450980392,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/626789ba1e7bdd00301bfa8d/c68adaff-7222-46b0-a919-7deb8eff29d3.jpg",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/69121848310981ec05e83b48d71fa5f1aa87f53b.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/69121848310981ec05e83b48d71fa5f1aa87f53b_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/69121848310981ec05e83b48d71fa5f1aa87f53b.jpg",
                segmentation_data: null,
                server_image_filename:
                  "69121848310981ec05e83b48d71fa5f1aa87f53b.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "women",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [2, 3, 4, 13],
            persona: [0, 2],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/626789ba1e7bdd00301bfa8d",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Jewellery"],
            remote_product_description: null,
            remote_product_id: "626789ba1e7bdd00301bfa8d",
            remote_product_size: null,
            remote_product_title: "Wide bracelet with logo",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [4, 5, 6],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [0],
            translations: null,
            updatedAt: "Tue, 12 Jul 2022 15:27:19 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/626789ba1e7bdd00301bfa8d",
                variant_id: "default",
              },
            ],
            weather: [0, 1, 2, 3, 4, 5, 6, 7],
          },
        ],
        market_id: [],
        occasion: [],
        outfit_id: "62c6d53c2a6b3e031c3c4a9a",
        outfit_image_url:
          "https://intelistyle-texel.s3.eu-west-1.amazonaws.com/looks/female/626789ca1e7bdd00301bfb29.png",
        persona: [],
        ranking: {
          "626789ba1e7bdd00301bfa8d": 3,
          "626789bf1e7bdd00301bfaca": 2,
          "626789c21e7bdd00301bfaf6": 1,
          "626789ca1e7bdd00301bfb29": 0,
        },
        season: null,
        skintone: [],
        source: null,
        styling_filters: [],
        type: "complete_the_look",
        weather: [],
      },
      {
        _user: null,
        approval_user: null,
        approved: 2,
        bodytype: [],
        brand_group: null,
        garments: [
          {
            _id: "62c699da39c7fe91d77f2dec",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [5, 6, 7, 8],
            chatbot_id: null,
            colour: {
              h: 0.9797008547008547,
              name: "indianred",
              s: 0.6724137931034483,
              v: 0.9098039215686274,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/626789a91e7bdd00301bf9b1/467bc2ae-3774-46d7-b242-e8e1df9167c9.jpg",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/76fbff277ae7099e6bc9e945e0bc8fe78076c7aa.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/76fbff277ae7099e6bc9e945e0bc8fe78076c7aa_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/76fbff277ae7099e6bc9e945e0bc8fe78076c7aa.jpg",
                segmentation_data: null,
                server_image_filename:
                  "76fbff277ae7099e6bc9e945e0bc8fe78076c7aa.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "men",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [16, 18, 21],
            persona: [6, 7, 8],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/626789a91e7bdd00301bf9b1",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Hoodies"],
            remote_product_description: null,
            remote_product_id: "626789a91e7bdd00301bf9b1",
            remote_product_size: null,
            remote_product_title: "Sweatshirt with logo",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [4, 5, 6, 7, 8, 9],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [0],
            translations: null,
            updatedAt: "Fri, 26 May 2023 14:58:04 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/626789a91e7bdd00301bf9b1",
                variant_id: "default",
              },
            ],
            weather: [4, 6, 7, 9],
          },
          {
            _id: "62c699da39c7fe91d77f2dbd",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [5, 6, 7, 8],
            chatbot_id: null,
            colour: {
              h: 0.970125786163522,
              name: "brown",
              s: 0.7066666666666667,
              v: 0.5882352941176471,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/6267899f1e7bdd00301bf943/b922faa2-ae6a-4ce4-8aa0-ceedd2508dc9.jpg",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/e4ef946ee018d2f2ef960c344b70450b038903df.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/e4ef946ee018d2f2ef960c344b70450b038903df_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/e4ef946ee018d2f2ef960c344b70450b038903df.jpg",
                segmentation_data: null,
                server_image_filename:
                  "e4ef946ee018d2f2ef960c344b70450b038903df.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "men",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [21],
            persona: [7],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/6267899f1e7bdd00301bf943",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Outerwear"],
            remote_product_description: null,
            remote_product_id: "6267899f1e7bdd00301bf943",
            remote_product_size: null,
            remote_product_title: "Windbreaker with hood",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [7, 8, 9],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [0],
            translations: null,
            updatedAt: "Fri, 26 May 2023 14:57:16 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/6267899f1e7bdd00301bf943",
                variant_id: "default",
              },
            ],
            weather: [0, 1, 2, 4, 5, 6, 7],
          },
          {
            _id: "62c699da39c7fe91d77f2dc1",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [6],
            chatbot_id: null,
            colour: {
              h: 0,
              name: "darkgray",
              s: 0,
              v: 0.6980392156862745,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/626789a01e7bdd00301bf94e/24abea44-8b71-4420-832c-a5d89b589805.jpg",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/e94bcc2a4e39c11a209103c33e4d7c09c9624462.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/e94bcc2a4e39c11a209103c33e4d7c09c9624462_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/e94bcc2a4e39c11a209103c33e4d7c09c9624462.jpg",
                segmentation_data: null,
                server_image_filename:
                  "e94bcc2a4e39c11a209103c33e4d7c09c9624462.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "men",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [16, 18, 21],
            persona: [7],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/626789a01e7bdd00301bf94e",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Trousers"],
            remote_product_description: null,
            remote_product_id: "626789a01e7bdd00301bf94e",
            remote_product_size: null,
            remote_product_title: "Straight pants with an overwhelmed waist",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [1, 2, 3, 10, 11, 12],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [0],
            translations: null,
            updatedAt: "Fri, 26 May 2023 14:57:19 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/626789a01e7bdd00301bf94e",
                variant_id: "default",
              },
            ],
            weather: [0, 1, 2, 3, 4, 5, 6, 7],
          },
          {
            _id: "62c699db39c7fe91d77f2ef0",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [5, 6, 7, 8],
            chatbot_id: null,
            colour: {
              h: 0.11111111111111123,
              name: "gray",
              s: 0.07894736842105254,
              v: 0.596078431372549,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/626789e31e7bdd00301bfbf9/150ea043-19e9-4b5d-ba93-e76b4cf1b864.jpg",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/3da999e12930c022fecb4cc02bad962387012a24.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/3da999e12930c022fecb4cc02bad962387012a24_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/3da999e12930c022fecb4cc02bad962387012a24.jpg",
                segmentation_data: null,
                server_image_filename:
                  "3da999e12930c022fecb4cc02bad962387012a24.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "men",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [21],
            persona: [6],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/626789e31e7bdd00301bfbf9",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Footwear"],
            remote_product_description: null,
            remote_product_id: "626789e31e7bdd00301bfbf9",
            remote_product_size: null,
            remote_product_title: "Sneakers Yeezy Boost 700 OG Wave Runner",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [4, 5, 6],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [0],
            translations: null,
            updatedAt: "Thu, 07 Jul 2022 12:43:24 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/626789e31e7bdd00301bfbf9",
                variant_id: "default",
              },
            ],
            weather: [0, 1, 2, 3, 4, 5, 6, 7],
          },
          {
            _id: "62c699db39c7fe91d77f2ee3",
            _user: "62c439a7e9a38c26d99f878e",
            additional_ids: null,
            age_ranges: null,
            approved: true,
            automated_description: null,
            automated_title: null,
            bodytype: [5, 6, 7, 8],
            chatbot_id: null,
            colour: {
              h: 0.08333333333333215,
              name: "darkgray",
              s: 0.011111111111111228,
              v: 0.7058823529411765,
            },
            createdAt: "Thu, 07 Jul 2022 08:31:22 GMT",
            currency_code: "GBP",
            date_added: null,
            discount: null,
            garment_images: [
              {
                bounding_box: null,
                embedding_data: {
                  approved: 0,
                  loss: 0,
                },
                local_image_filename: "",
                position: "",
                remote_image_url:
                  "https://tapps-widget-dev.s3.eu-north-1.amazonaws.com/shops/6153fc53825dd50006d7267d/products/626789e01e7bdd00301bfbde/fcc803f0-0985-452d-bd61-3c4b623db191.jpg",
                remote_image_url_small: null,
                s3_segmentation_mask_url: null,
                s3_segmented_image_url: null,
                s3_url:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/4d2b9a00d015f296987322d7d68f5c54488ebf57.jpg",
                s3_url_removed_bg:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/removed_background/4d2b9a00d015f296987322d7d68f5c54488ebf57_rm_bg.png",
                s3_url_resized:
                  "https://stylr-ai-engine-srv-data.s3-eu-west-1.amazonaws.com/srv/data/serving/resized/4d2b9a00d015f296987322d7d68f5c54488ebf57.jpg",
                segmentation_data: null,
                server_image_filename:
                  "4d2b9a00d015f296987322d7d68f5c54488ebf57.jpg",
                server_image_filename_small: null,
              },
            ],
            gender: "men",
            is_priority: null,
            labels: null,
            languages: null,
            local_id: null,
            matching_garment_ids: null,
            occasion: [],
            persona: [5, 6, 8],
            price: 119,
            processing_status: {
              status: "complete",
            },
            product_url:
              "https://intelistyledev.myshopify.com/products/626789e01e7bdd00301bfbde",
            remote_brand: "ACME",
            remote_outfit_id: null,
            remote_product_categories: ["Accessories"],
            remote_product_description: null,
            remote_product_id: "626789e01e7bdd00301bfbde",
            remote_product_size: null,
            remote_product_title: "Aviators sunglasses with logo",
            remote_url: null,
            shop: null,
            shopifyInventoryItems: null,
            similar_data: null,
            size: null,
            skintone: [1, 2, 3, 10, 11, 12],
            source: "texelmoda",
            stock: 1,
            stock_level: 1,
            styling_filters: [0],
            translations: null,
            updatedAt: "Wed, 13 Jul 2022 09:43:19 GMT",
            variantId: null,
            variant_data: [
              {
                currency_code: "GBP",
                price: 119,
                stock_level: 1,
                url: "https://intelistyledev.myshopify.com/products/626789e01e7bdd00301bfbde",
                variant_id: "default",
              },
            ],
            weather: [1, 3, 5, 7],
          },
        ],
        market_id: [],
        occasion: [],
        outfit_id: "62c6d5732a6b3e031c3c4b0f",
        outfit_image_url:
          "https://intelistyle-texel.s3.eu-west-1.amazonaws.com/looks/male/626789a91e7bdd00301bf9b1.png",
        persona: [],
        ranking: {
          "6267899f1e7bdd00301bf943": 0,
          "626789a01e7bdd00301bf94e": 2,
          "626789a91e7bdd00301bf9b1": 1,
          "626789e01e7bdd00301bfbde": 4,
          "626789e31e7bdd00301bfbf9": 3,
        },
        season: null,
        skintone: [],
        source: null,
        styling_filters: [],
        type: "complete_the_look",
        weather: [],
      },
    ],
  }